### PR TITLE
hello-world: Added hello-world exercise

### PR DESCRIPTION
**Pull request by McFadge**
Added the hello-world exercise, based upon examples in other tracks.

Sorry for the multiple commits! I was trying to squash by using a different branch but it seems that didn't go to plan.

### CODE REVIEW

**Comment by McFadge** [comment]
Just bumping this to see if I did the right thing to add an exercise. Gives me a point of reference for porting any other tasks.

**Comment by kytrinyx** [comment]
Oh! Sorry I missed this. Yepp, it looks like you got all the fiddly details right. Would you mind squashing the commits?

**Comment by McFadge** [comment]
Phew, managed to do it and learned some new git today.

**Comment by kytrinyx** [comment]
Sweet!

**Pull request merged**
