### PR TITLE
Remove explicitly passed string length in Hamming

### LINKED ISSUE #41: Hamming - use strlen instead of explicitly passing the length of each string
Especially since the tests pass the length as a magic number.

### PR DESCRIPTION
**Pull request by ryanplusplus**
I cleaned up the `compute` interface by removing explicitly passed (and error-prone) string length and calculated with `strlen` instead.

Closes #41

### CODE REVIEW

**Comment by ryanplusplus** [comment]
I also took this opportunity to make the formatting more consistent with the provided example. If we're unhappy with this direction we can address it in #40.

**Comment by palisaide** [comment]
Looks good.

**Comment by krbullock** [comment]
It should probably have some concept of a max string length that it will handle, and use `strnlen()` to find the length in the reference solution instead.

**Comment by ryanplusplus** [comment]
@krbullock do you mean to use that to prevent a denial of service attack with an incredibly long string? I can see how that would help someone learn about `strnlen`, but I'm not really seeing the utility in setting an arbitrary limit to the strings that can be compared.

**Comment by krbullock** [comment]
Yeah, my thought is we should introduce people to _safe_ string handling in C from the beginning. Arbitrary length limits suck but are the reality in real C code in my (somewhat limited) experience.

Alternatively, maybe the caller could pass a single max length for both strings? Any safe code that would call `compute` would have to know the max length of the strings it was passing, whether they were static or user-provided.

**Comment by ryanplusplus** [comment]
@krbullock the issue I have is that it's weird for this library to enforce length limits on strings that a _client_ provides. While it's a reality in C that you have to deal with arbitrary length limits, if the client is managing the memory then the client (and not the library) needs to deal with any weird length limitations.

**Comment by palisaide** [comment]
I'm good with these changes.  Can we resolve conflicts and merge?

**Comment by ryanplusplus** [comment]
Conflicts resolved and updated style applied.

**Pull request merged**
