### PR TITLE
Update README.md to include details of example solutions

### LINKED ISSUE #103: Add an explanation of example.c/h to README
The main contributing guide explains a little about how example solutions work across the Exercism tracks, but the usage here of example.c, example.h, and the provided headers should be explicitly explained in our README.

The same patch would likely apply to the exercism/xcpp repo as well.

### PR DESCRIPTION
**Pull request by palisaide**
Closes #103 .  Tried to keep it brief, but maybe we need more details.

### CODE REVIEW

**Comment by wolf99** [comment]
Maybe could add a small bit abut the directory structure used, as this is slightly different from that outlined in the referenced anatomy section of the README?

**Comment by patricksjackson** [comment]
Three extra details I think need to be included.

1. Note the reason for this is that files with `example` in the name are skipped when downloading to the client. It's not all that clear in the x-common guide.
2. References to the file names in the code always point to the expected name of the files and not `example.c/h`. (e.g. Include guards and statements)
3. The naming scheme means the checked in code is only able to compile using the `bin\run-tests` script, which will rename the files correctly.

**Comment by wolf99** [comment]
Should this have been protected from the probot as part of #8 ?

**Comment by ryanplusplus** [comment]
@wolf99 I think we can keep the issue open, but I don't want to merge this without @patricksjackson's comments addressed and it has been several months. So, I think we should keep this PR closed, but if you want to pick up @palisaide's changes and open a new PR I'd be happy to review and merge.

**Pull request closed without merging**
