### PR TITLE
Prevent segfault early on in TDD cycle per issue #116

### PR DESCRIPTION
**Pull request by wolf99**
Also adjust strlen argument as mentioned by @patricksjackson, also in issue #116

### CODE REVIEW

**Comment by wolf99** [comment]
Fixes #116

**Comment by wolf99** [comment]
I haven't tested this out but it seems that the options used in `indent.sh` differ from the Linux style, not only by `-i3` but also by `-nut`, which may be where the difference is caused. If this *is* the case I would suggest changing either the rule in indent.sh, or the suggested command in README.md that uses the `-linux` option.

**Comment by patricksjackson** [comment]
LGTM :+1:

I'll merge it myself in a few days if the other maintainers don't weigh in by then. My only mild concern is getting someone to confirm that the new `strncmp` argument is a good idea.

**Comment by palisaide** [comment]
I'm questioning whether the `+ 1` will actually do anything.  The documentation for `strncmp()` states that it will terminate whenever a null terminator is reached in either string.  So, wouldn't it just stop as soon as it gets to the end of `dna`?

Otherwise, looks good to me.

**Comment by patricksjackson** [comment]
@palisaide The point of that extra 1 is to make sure that `rna` is the same length as `expected`. e.g. if `rna = "ABC"` and `expected = "AB"` then without the +1 it wouldn't find the difference. (I just confirmed that this is the case).

I now realize though that since we're already relying on both `dna` and `expected` to be valid NULL-terminated strings, replacing the `strncmp` with just a call to `strcmp` is probably better anyways. It's safe as long as we know one of the strings is valid.

**Comment by wolf99** [comment]
@patricksjackson & @palisaide, please expand my commit message for f5ba2f6 above to see reasoning about further changes I have made.

**Comment by ryanplusplus** [comment]
@palisaide @patricksjackson this looks good to me. Is there any reason not to merge?

**Pull request merged**
